version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: weblinuxgame/ipservice
    volumes:
      - ".docker/tmp/db:/app/tmp/db:rw"
      - ".docker/etc:/app/etc"
    ports:
    -  "28000:8080"
    restart: always