version: "3"

services:

  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: weblinuxgame/ipservice:${SERVICE_VERSION:-latest}
    container_name: ipService
    hostname: ipService
    volumes:
      - ".docker/tmp/db:/app/tmp/db:rw"
      - ".docker/etc:/app/etc"
      - ".docker/logs:/app/logs:rw"
    ports:
    -  "28000:8080"
    restart: always
    networks:
      - bongolive

networks:
  bongolive:
    external: true