// Code generated by goctl. DO NOT EDIT.
package types

type GetIpRequest struct {
	AccessKey string `query:"accessKey,optional=1" desc:"应用accessKey" name:"accessKey"`
	IpAddr    string `query:"ip,optional=1" desc:"ip地址" name:"ip"`
}

type GetIpResponseData struct {
	Ip       string `json:"ip" desc:"ip" name:"ip"`
	CityId   int64  `json:"city_id" desc:"城市Id" name:"city_id"`
	Country  string `json:"country" desc:"国家" name:"country"`
	District string `json:"district" desc:"区域" name:"district"`
	Province string `json:"province" desc:"省份" name:"province"`
	City     string `json:"city" desc:"城市" name:"city"`
	ISP      string `json:"ISP" desc:"ISP" name:"ISP"`
}

type GetIpResponse struct {
	Msg  string             `json:"msg" desc:"业务提示" name:"msg"`
	Code int                `json:"code" desc:"业务码" name:"code"`
	Data *GetIpResponseData `json:"data" desc:"消息体" name:"data"`
}
